apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-world
  namespace: jackie
  labels:
    app: hello-world
spec:
  source:
    type: Git
    git:
      uri: https://github.com/xiujungao/jackie.git
      ref: master
    contextDir: spring-boot-hello-world
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-21:1.18
  output:
    to:
      kind: ImageStreamTag
      name: "hello-world:latest"
  triggers:
    - type: GitHub
      github:
        secret: manage
    - type: ConfigChange
    - type: ImageChange
