kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hello-world-hpa
  namespace: jackie
  labels:
    app: hello-world
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
