apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-hello-world
  namespace: jackie
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/crc/local-pv/hello-world # path inside the CRC VM
