apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
  namespace: jackie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  volumeName: local-pv-hello-world # <-- hard bind to this PV. however, this is not recommended for production
  storageClassName: "" # <-- disable dynamic provisioning
